CREATE TABLE DEPT (
    DEPT_NO TINYINT(2) PRIMARY KEY,
    DNOM VARCHAR(14),
    LOC VARCHAR(14)
);

CREATE TABLE  PRODUCTE (
    PROD_NUM INT(6) PRIMARY KEY,
    DESCRIPCIO VARCHAR(30)
);

CREATE TABLE CLIENT (
    CLIENT_COD INT(6) PRIMARY KEY,
    NOM VARCHAR(45),
    ADRECA VARCHAR(40),
    CIUTAT VARCHAR(30),
    ESTAT VARCHAR(2),
    CODI_POSTAL VARCHAR(9),
    AREA SMALLINT(3),
    TELEFON VARCHAR(9),
    REPR_COD SMALLINT(4),
    LIMIT_CREDIT DECIMAL(9,2),
    OBSERVACIONS TEXT
);

CREATE TABLE EMP (
    EMP_NO SMALLINT(4) PRIMARY KEY,
    COGNOM VARCHAR(10),
    OFICI VARCHAR(10),
    CAP SMALLINT(4),
    DATA_ALTA DATE,
    SALARI INT,
    COMISSIO INT,
    DEPT_NO TINYINT(2),
    FOREIGN KEY (DEPT_NO) REFERENCES DEPT(DEPT_NO)
);

CREATE TABLE DETALL (
    DETALL_NUM SMALLINT(4) PRIMARY KEY,
    PREU_VENDA DECIMAL(8,2),
    QUANTITAT INT(8),
    IMPORT DECIMAL(8,2),
    COM_NUM SMALLINT(4),
    PROD_NUM INT(6),
    FOREIGN KEY (COM_NUM) REFERENCES COMANDA(COM_NUM),
    FOREIGN KEY (PROD_NUM) REFERENCES PRODUCTE(PROD_NUM) 
);

CREATE TABLE COMANDA (
    COM_NUM SMALLINT(4) PRIMARY KEY,
    COM_DATA DATE,
    CLIENT_COD INT(6),
    COM_TIPUS CHAR(1),
    DATA_TRAMESA DATE,
    TOTAL DECIMAL(8,2),
    FOREIGN KEY (CLIENT_COD) REFERENCES CLIENT (CLIENT_COD)
);


INSERT INTO DEPT(DEPT_NO, DNOM, LOC) VALUES
(1, 'AQUARIUSITO', 'MARRUECOS'),
(2, 'ESCOBADERO', 'ANTARTIDA');

INSERT INTO PRODUCTE() VALUES
(),
();

INSERT INTO CLIENT() VALUES
(),
();

INSERT INTO EMP() VALUES
(),
();

INSERT INTO DETALL() VALUES
(),
();

INSERT INTO COMANDA() VALUES
(),
();